### PR TITLE
Building off your success

### PR DESCRIPTION
**Pull request by ijlyttle**
Hi @AliciaSchep,

I made a first pass at extending the knit-print interception to `svg` and `pdf`. I'll want another day or so to clean up the documentation, but I wanted you to have a look at it to see what you think.

The `svg` option works for the README; maybe I should try a getting-started vignette (like an actual vignette) to try out the `pdf` option. I got it to work for a toy example, but it would be nice to point at a real example.

I'll let you know when I think it's all ready, but I don't think I will want to take too much longer.

Thanks!

### CODE REVIEW

**Comment by AliciaSchep** [comment]
Looks good!  Happy to merge this now, or did you want to make another update?

**Comment by AliciaSchep** [comment]
I'll go ahead and merge this actually -- if more changes are needed, why don't we redirect the PR on the main repo to a feature branch & merge it to that feature branch; then additional changes can be made or PR-ed to that branch?

**Comment by ijlyttle** [comment]
Sounds good - I think we are mostly there, I like your suggestion that we build a feature branch on the main repo, and redirect it there! Thanks!

**Comment by ijlyttle** [comment]
Just to note that the feature-branch is now `rmd-intercept`

**Pull request merged**
